pipelines:
  branches:
    master:
      - step:
          name: Build and Test
          image: maven:3.6.3-jdk-8
          caches:
            - maven
          script:
            - mvn clean package
          artifacts:
            - webapp/target/webapp.war

