pipelines:
  branches:
    master:
      - step:
          name: Build and test
          image: maven:3.6.3-jdk-8
          caches:
            - maven
          script:
            - export repoDir="$PWD"
            - cd "$repoDir/frontend"
            - export packageFile="package.json"
            - sed -i "s/ssh.slococo.com.ar:2557/pawserver.it.itba.edu.ar/g" "$packageFile"
            - export serverFile="src/utils/server.js"
            - sed -i -e "1d" "$serverFile"
            - sed -i "s/dev/false/g" "$serverFile"
            - cd "$repoDir/backend"
            - export webConfigFile="webapp/src/main/java/ar/edu/itba/paw/webapp/config/WebConfig.java"
            - sed -i "s/@PropertySource(\"classpath:config.properties\")//g" "$webConfigFile"
            - sed -i "s/env.getProperty(\"dbUsername\")/\"$PAW_BOTTLER_USER\"/g" "$webConfigFile"
            - sed -i "s/env.getProperty(\"dbPassword\")/\"$PAW_BOTTLER_PASS\"/g" "$webConfigFile"
            - sed -i "s/env.getProperty(\"dbURL\")/\"jdbc:postgresql:\/\/10.16.1.110\/$PAW_BOTTLER_USER\"/g" "$webConfigFile"
            - sed -i "s/env.getProperty(\"mailUsername\")/\"bottlerpass@zohomail.com\"/g" "$webConfigFile"
            - sed -i "s/env.getProperty(\"mailPassword\")/\"$PAW_BOTTLER_MAILPASS\"/g" "$webConfigFile"
            - sed -i "s/env.getProperty(\"mail\")/\"false\"/g" "$webConfigFile"
            - sed -i "s/env.getProperty(\"debug\")/\"false\"/g" "$webConfigFile"
            - export codeServiceFile="service/src/main/java/ar/edu/itba/paw/service/CodeServiceImpl.java"
            - sed -i "s/@PropertySource(\"classpath:config.properties\")//g" "$codeServiceFile"
            - sed -i "s/env.getProperty(\"encPassword\")/\"$PAW_BOTTLER_ENCPASS\"/g" "$codeServiceFile"
            - sed -i "s/env.getProperty(\"encSalt\")/\"$PAW_BOTTLER_ENCSALT\"/g" "$codeServiceFile"
            - export tokenConfigFile="webapp/src/main/java/ar/edu/itba/paw/webapp/auth/JwtTokenUtils.java"
            - sed -i "s/env.getProperty(\"secret\")/\"$PAW_BOTTLER_ENCPASS\"/g" "$tokenConfigFile"
            - sed -i "s/env.getProperty(\"baseUrl\")/\"http:\/\/pawserver.it.itba.edu.ar\/paw-2022a-04\"/g" "$tokenConfigFile"
            - export responseFilterFile="webapp/src/main/java/ar/edu/itba/paw/webapp/config/ResponseFilter.java"
            - sed -i "s/env.getProperty(\"cors\")/\"false\"/g" "$responseFilterFile"
            - export eventControllerFile="webapp/src/main/java/ar/edu/itba/paw/webapp/controller/EventController.java"
            - sed -i "s/env.getProperty(\"baseUrl\")/\"http:\/\/pawserver.it.itba.edu.ar\/paw-2022a-04\"/g" "$eventControllerFile"
            - export bookingControllerFile="webapp/src/main/java/ar/edu/itba/paw/webapp/controller/BookingController.java"
            - sed -i "s/env.getProperty(\"baseUrl\")/\"http:\/\/pawserver.it.itba.edu.ar\/paw-2022a-04\"/g" "$bookingControllerFile"
            - unset CI
            - mvn clean package
          artifacts:
            - backend/webapp/target/webapp.war
      - step:
          name: Copy files
          deployment: staging
          script:
            - apt-get update && apt-get install -y sshpass
            - ssh-keyscan pampero.itba.edu.ar >> ~/.ssh/known_hosts
            - export SSHPASS="$PAW_BOTTLER_SERPASS"
            - sshpass -e scp backend/webapp/target/webapp.war slococo@pampero.itba.edu.ar:/home/slococo/app.war
      - step:
          name: Deploy
          deployment: production
          trigger: manual
          script:
            - apt-get update && apt-get install -y sshpass
            - ssh-keyscan pampero.itba.edu.ar >> ~/.ssh/known_hosts
            - export SSHPASS="$PAW_BOTTLER_SERPASS"
            - sshpass -e ssh slococo@pampero.itba.edu.ar "./deploy"
 
